imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: ru
    mailer_parameters:
        send_to:
          - 'uvelife@gmail.com'
        send_from: 'no-reply@uvelife.com'
    recaptcha:
      site_key: "6LfJJCsUAAAAADpp4W_SLgJDaL6cxYTYaw1_CvOP"
      secret_key: "6LfJJCsUAAAAAIvq-Atj_KEF18zV9WLv_v1MjhKt"

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    translator: { fallbacks: ["%locale%"] }

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'SiteUploadBundle:Form:fields.html.twig'
        - 'SonataCoreBundle:Form:datepicker.html.twig'
        - 'SiteFrontendBundle:Form:_range_field.html.twig'
    globals:
        recaptcha: '%recaptcha%'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        mapping_types:
            enum: string
            set: string
            varbinary: string
            tinyblob: text
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            numeric_functions:
                Rand: Site\BackendBundle\DQL\RandFunction
# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
#    spool:     { type: memory }

assetic:
    debug:          '%kernel.debug%'
    use_controller: false
    filters:
        cssrewrite: ~
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yui_compressor2.4.7.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yui_compressor2.4.7.jar"

#Knp Pager
knp_paginator:
    page_range: 150                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:sliding.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: Site\BackendBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"

#DoctrineMigrations
doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Site\BackendBundle\Migrations
    table_name: migration_versions
    name: Site Migrations

#TinyMCE Bundle
stfalcon_tinymce:
    tinymce_jquery: true
    selector: ".tinymce"
#    base_url: "http://example.loc/"
    # this parameter may be included if you need to override the assets_base_urls for your template engine (to override a CDN base url)
    # Get current language from the parameters.ini
    language: "%locale%"
#    entity_encoding: "raw"
    # Custom buttons
    tinymce_buttons:
#        stfalcon: # Id of the first button
#            title: "Stfalcon"
#            image: "http://stfalcon.com/favicon.ico"
    theme:
        # Simple theme: same as default theme
        simple:
             plugins:
                 - "advlist autolink lists link image charmap print preview hr anchor pagebreak"
                 - "searchreplace wordcount visualblocks visualchars code fullscreen"
                 - "insertdatetime media nonbreaking save table directionality"
                 - "paste textcolor"
             menubar: false
             toolbar1: " bold italic | fontsizeselect forecolor backcolor | bullist numlist outdent indent | link | code "
             image_advtab: true
             fontsize_formats: '8px 10px 12px 14px 18px 24px 36px 40px 48px 60px'
             relative_urls: false
             force_br_newlines : false
             force_p_newlines : false
             file_browser_callback : elFinderBrowser
             relative_urls: false
        medium:
             plugins:
                 - "advlist autolink lists link image charmap print preview hr anchor pagebreak"
                 - "searchreplace wordcount visualblocks visualchars code fullscreen"
                 - "insertdatetime media nonbreaking save table contextmenu directionality"
                 - "emoticons template paste textcolor"
             toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
             toolbar2: "print preview media | forecolor backcolor emoticons | stfalcon | example"
             image_advtab: true
             templates:
                 - {title: 'Test template 1', content: 'Test 1'}
                 - {title: 'Test template 2', content: 'Test 2'}
             file_browser_callback : elFinderBrowser
             relative_urls: false
        # BBCode tag compatible theme (see http://www.bbcode.org/reference.php)
        bbcode:
             plugins: ["bbcode, code, link, preview"]
             menubar: false
             toolbar1: "bold,italic,underline,undo,redo,link,unlink,removeformat,cleanup,code,preview"
             relative_urls: false

#Fm-Elinder
fm_elfinder:
    instances:
        default:
            locale: "%locale%" # defaults to current request locale
            editor: tinymce4 # other options are tinymce, tinymce4, form, custom and simple
            fullscreen: true # defaults true, applies to simple and ckeditor editors
            theme: smoothness # jquery theme
            include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
            connector:
                debug: false # defaults to false
                roots:       # at least one root must be defined
                    uploads:
                        show_hidden: false # defaults to false
                        driver: LocalFileSystem
                        path: uploads/tinymce-uploads
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg','application/pdf']
                        upload_deny: ['all']
                        upload_max_size: 2M

#Doctrine Extension
stof_doctrine_extensions:
    default_locale: ru
    translation_fallback: true
    persist_default_translation: false
    orm:
        default:
            timestampable: true
            sluggable: true
            translatable: true
            sortable: true

sonata_block:
    default_contexts: [cms]
    blocks:

        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.admin.block.search_result:
            contexts: [admin]

sonata_admin:
    title:                'UveLife Admin'
    title_logo:           bundles/sitefrontend/images/gray-crystal.png
    templates:
        layout: SiteBackendBundle::layout.html.twig
    security:
        handler: sonata.admin.security.handler.role
    dashboard:
        groups:
            Product:
                label: Product
                label_catalogue: SiteBackendBundle
                items:
                    - site_backend.admin.product
                    - site_backend.admin.load.xml
                    - site_backend.admin.set
            Tags:
                label: Tags
                label_catalogue: SiteBackendBundle
                items:
                    - site_backend.admin.insertion.color
                    - site_backend.admin.ring.size
                    - site_backend.admin.chain.size
                    - site_backend.admin.share.tag
                    - site_backend.admin.news.tag
            Category:
                label: Category
                label_catalogue: SiteBackendBundle
                items:
                    - site_backend.admin.category
                    - site_backend.admin.sub.category
            Order:
                label: Order
                label_catalogue: SiteBackendBundle
                items:
                    - site_backend.admin.order
            News:
                label: News
                label_catalogue: SiteBackendBundle
                items:
                    - site_backend.admin.news
                    - site_backend.admin.static.page.content
                    - site_backend.admin.slider
                    - site_backend.admin.static.seo.pages
            Contacts:
                label: Contacts
                label_catalogue: SiteBackendBundle
                items:
                    - site_backend.admin.contacts
                    - site_backend.admin.callback
        blocks:
            -
                position: left
                type: sonata.admin.block.admin_list
                settings:
                    groups: [Product, Category, News]
            -
                position: right
                type: sonata.admin.block.admin_list
                settings:
                    groups: [Tags, Order]

#Upload bundle
site_upload:
    web_dir: 'www'
    temp_upload_dir: "uploads/temp"
    types:
        default:
            type: file
            format: 'txt, pdf, doc'  #client validation
            mime_type: ['text/plain', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/pdf'] #list mime types  http://www.webmaster-toolkit.com/mime-types.shtml
            upload_dir: '/uploads'
            max_size: '47612000' #bytes
        product_icon:
            type: image
            mime_type: []  # default
            format: 'jpg,gif,png'
            upload_dir: '/uploads/products'
            max_size: '4761200' #bytes
            thumbnails:
                extra_small:
                   width: 100
                   height: 100
                   action: exact_resize
                   watermark: 'bundles/sitefrontend/images/watermark-01.png'
                small:
                   width: 350
                   height: 350
                   action: resize_and_crop
                   watermark: 'bundles/sitefrontend/images/watermark-01.png'
                big:
                   width: 710
                   height: 510
                   action: exact_resize
                   watermark: 'bundles/sitefrontend/images/watermark-01.png'
        set_icon:
            type: image
            mime_type: []  # default
            format: 'jpg,gif,png'
            upload_dir: '/uploads/sets'
            max_size: '4761200' #bytes
            thumbnails:
                extra_small:
                   width: 100
                   height: 100
                   action: exact_resize
                   watermark: 'bundles/sitefrontend/images/watermark-01.png'
                small:
                   width: 350
                   height: 350
                   action: resize_and_crop
                   watermark: 'bundles/sitefrontend/images/watermark-01.png'
                big:
                   width: 710
                   height: 510
                   action: exact_resize
                   watermark: 'bundles/sitefrontend/images/watermark-01.png'
        news_icon:
            type: image
            mime_type: []  # default
            format: 'jpg,gif,png'
            upload_dir: '/uploads/news'
            max_size: '4761200' #bytes
            thumbnails:
                small:
                   width: 350
                   height: 350
                   action: resize_and_crop
                   watermark: 'bundles/sitefrontend/images/watermark-01.png'
                big:
                   width: 710
                   height: 510
                   action: exact_resize
                   watermark: 'bundles/sitefrontend/images/watermark-01.png'
        product_gallery_icon:
            type: image
            mime_type: []  # default
            format: 'jpg,gif,png'
            upload_dir: '/uploads/product-gallery'
            max_size: '4761200' #bytes
            thumbnails:
                extra_small:
                   width: 100
                   height: 100
                   action: exact_resize
                   watermark: 'bundles/sitefrontend/images/watermark-01.png'
                small:
                   width: 350
                   height: 350
                   action: exact_resize
                   watermark: 'bundles/sitefrontend/images/watermark-01.png'
                big:
                   width: 710
                   height: 510
                   action: exact_resize
                   watermark: 'bundles/sitefrontend/images/watermark-01.png'
        set_gallery_icon:
            type: image
            mime_type: []  # default
            format: 'jpg,gif,png'
            upload_dir: '/uploads/set-gallery'
            max_size: '4761200' #bytes
            thumbnails:
                extra_small:
                   width: 100
                   height: 100
                   action: exact_resize
                   watermark: 'bundles/sitefrontend/images/watermark-01.png'
                small:
                   width: 350
                   height: 350
                   action: exact_resize
                   watermark: 'bundles/sitefrontend/images/watermark-01.png'
                big:
                   width: 710
                   height: 510
                   action: exact_resize
                   watermark: 'bundles/sitefrontend/images/watermark-01.png'
        slider:
            type: image
            mime_type: []  # default
            format: 'jpg,gif,png'
            upload_dir: '/uploads/slides'
            max_size: '4761200' #bytes
            thumbnails:
                big:
                   width: 850
                   height: 370
                   action: exact_resize
                   watermark: 'bundles/sitefrontend/images/watermark-01.png'