site_frontend:
    resource: "@SiteFrontendBundle/Resources/config/routing.yml"
    prefix:   /

#Site Upload Bundle
site_upload:
    resource: "@SiteUploadBundle/Resources/config/routing.yml"
    prefix:   /upload-bundle/

elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

site_backend:
    resource: "@SiteBackendBundle/Resources/config/routing.yml"
    prefix:   /admin

_sonata_admin:
  resource: .
  type: sonata_admin
  prefix: /admin