site_upload_bundle_handle_file:
    path:  /handle-single-file/
    defaults: { _controller: SiteUploadBundle:Default:upload}

site_upload_bundle_crop_file:
    path:  /crop-single-file/
    defaults: { _controller: SiteUploadBundle:Default:crop}