services:
#twig extencion
    json.decode.twig_extension:
        class: Site\UploadBundle\Twig\Extension\JsonDecodeExtension
        public: false
        arguments: ["@service_container"]
        tags:
          - { name: twig.extension }

    json.detect.twig_extension:
        class: Site\UploadBundle\Twig\Extension\JsonDetectExtension
        public: false
        arguments: ["@service_container"]
        tags:
          - { name: twig.extension }
#file handler
    upbeat_file_upload.handler:
        class: Site\UploadBundle\Services\FileHandler
        arguments:
          - "@session"
          - "%site_upload.types%"
          - "%site_upload.temp_upload_dir%"
          - "%site_upload.web_dir%"
          - "%kernel.root_dir%"

    upbeat_file_upload.form.type:
        class: Site\UploadBundle\Form\UpbeatUploadType
        arguments: ["@security.csrf.token_manager", "@session"]
        tags:
            - { name: form.type }

#update and remove listeners
    file.delete.listener:
        class: Site\UploadBundle\EventListener\FileDeleteListener
        arguments:
            - "@upbeat_file_upload.handler"
        tags:
            - { name: doctrine.event_listener, event: preRemove }
    file.update.listener:
        class: Site\UploadBundle\EventListener\FileUpdateListener
        arguments:
            - "@upbeat_file_upload.handler"
            - "%site_upload.web_dir%"
            - "%kernel.root_dir%"
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
