#**************************************Order*************************************************************************#
site_backend_top_blocks_render:
  path:  /custom-top-blocks
  defaults: { _controller: SiteBackendBundle:Default:renderTopBlocks}



