parameters:
    xml_temp_upload_dir: "/uploads/xml-temp"
    logger_save_dir: "/xml-files/"
services:
###############################################xml-load#################################################################
    upbeat.xml.loader:
        class: Site\BackendBundle\LoadXml\XmlLoader
        arguments:
            - "@service_container"

    upbeat.xml.load.logger:
        class: Site\BackendBundle\LoadXml\XmlLoaderLogger
        arguments:
            - "@service_container"

    custom.event.xml_parse_error:
        class: Site\BackendBundle\Exceptions\ExceptionListener
        tags:
            -
              name: kernel.event_listener
              event: kernel.exception
              method: onKernelException
        arguments:
            container: "@service_container"
###############################################end-xml-load#############################################################
    site_backend.admin.product:
        class: Site\BackendBundle\Admin\ProductAdmin
        arguments:
            - ~
            - Site\BackendBundle\Entity\Product
            - ~
            - "@service_container"
            - "@doctrine.orm.default_entity_manager"
            - "@upbeat_file_upload.handler"
        tags:
            - {name: sonata.admin, manager_type: orm,group: "product", show_in_dashboard: true, label: product}
        calls:
            - [ setTemplate, [outer_list_rows_mosaic, SiteBackendBundle:ProductAdmin:list_outer_rows_mosaic.html.twig]]

    site_backend.admin.set:
        class: Site\BackendBundle\Admin\SetAdmin
        arguments:
            - ~
            - Site\BackendBundle\Entity\Set
            - ~
            - "@service_container"
            - "@doctrine.orm.default_entity_manager"
            - "@upbeat_file_upload.handler"
        tags:
            - {name: sonata.admin, manager_type: orm,group: "product", show_in_dashboard: true, label: set}

    site_backend.admin.slider:
        class: Site\BackendBundle\Admin\SliderAdmin
        arguments:
            - ~
            - Site\BackendBundle\Entity\Slider
            - ~
            - "@service_container"
            - "@doctrine.orm.default_entity_manager"
            - "@upbeat_file_upload.handler"
        tags:
            - {name: sonata.admin, manager_type: orm,group: "news", show_in_dashboard: true, label: slider}

    site_backend.admin.product.gallery:
        class: Site\BackendBundle\Admin\ProductGalleryAdmin
        arguments:
            - ~
            - Site\BackendBundle\Entity\ProductGallery
            - ~
            - "@service_container"
            - "@doctrine.orm.default_entity_manager"
            - "@upbeat_file_upload.handler"
        tags:
            - {name: sonata.admin, manager_type: orm,group: "", show_in_dashboard: false, label: ProductGallery}

    site_backend.admin.set.gallery:
        class: Site\BackendBundle\Admin\SetGalleryAdmin
        arguments:
            - ~
            - Site\BackendBundle\Entity\SetGallery
            - ~
            - "@service_container"
            - "@doctrine.orm.default_entity_manager"
            - "@upbeat_file_upload.handler"
        tags:
            - {name: sonata.admin, manager_type: orm,group: "", show_in_dashboard: false, label: SetGallery}

    site_backend.admin.news:
        class: Site\BackendBundle\Admin\NewsAdmin
        arguments:
            - ~
            - Site\BackendBundle\Entity\News
            - ~
            - "@service_container"
            - "@doctrine.orm.default_entity_manager"
            - "@upbeat_file_upload.handler"
        tags:
            - {name: sonata.admin, manager_type: orm,group: "news", show_in_dashboard: true, label: News}
        calls:
            - [ setTemplate, [outer_list_rows_mosaic, SiteBackendBundle:ProductAdmin:list_outer_rows_mosaic.html.twig]]

    site_backend.admin.static.page.content:
        class: Site\BackendBundle\Admin\StaticPageContentAdmin
        arguments:
            - ~
            - Site\BackendBundle\Entity\StaticPageContent
            - ~
        tags:
            - {name: sonata.admin, manager_type: orm,group: "news", show_in_dashboard: true, label: StaticText}

    site_backend.admin.static.seo.pages:
        class: Site\BackendBundle\Admin\StaticSeoPagesAdmin
        arguments:
            - ~
            - Site\BackendBundle\Entity\StaticSeoPages
            - ~
        tags:
            - {name: sonata.admin, manager_type: orm,group: "news", show_in_dashboard: true, label: StaticSeoText}

    site_backend.admin.insertion.color:
        class: Site\BackendBundle\Admin\InsertionColorAdmin
        arguments:
            - ~
            - Site\BackendBundle\Entity\InsertionColor
            - PixSortableBehaviorBundle:SortableAdmin
        tags:
            - {name: sonata.admin, manager_type: orm,group: "tags", show_in_dashboard: true, label: insertionColor}

    site_backend.admin.share.tag:
        class: Site\BackendBundle\Admin\ShareTagAdmin
        arguments:
            - ~
            - Site\BackendBundle\Entity\ShareTag
            - ~
        tags:
            - {name: sonata.admin, manager_type: orm,group: "tags", show_in_dashboard: true, label: shareTag}


    site_backend.admin.callback:
        class: Site\BackendBundle\Admin\CallbackAdmin
        arguments:
            - ~
            - Site\BackendBundle\Entity\Callback
            - ~
        tags:
            - {name: sonata.admin, manager_type: orm,group: "contacts", show_in_dashboard: true, label: Callback}

    site_backend.admin.contacts:
        class: Site\BackendBundle\Admin\ContactsAdmin
        arguments:
            - ~
            - Site\BackendBundle\Entity\Contacts
            - ~
        tags:
            - {name: sonata.admin, manager_type: orm,group: "contacts", show_in_dashboard: true, label: Contacts}

    site_backend.admin.news.tag:
        class: Site\BackendBundle\Admin\NewsTagAdmin
        arguments:
            - ~
            - Site\BackendBundle\Entity\NewsTag
            - ~
        tags:
            - {name: sonata.admin, manager_type: orm,group: "tags", show_in_dashboard: true, label: newsTag}

    site_backend.admin.ring.size:
        class: Site\BackendBundle\Admin\RingSizeAdmin
        arguments:
            - ~
            - Site\BackendBundle\Entity\RingSize
            - PixSortableBehaviorBundle:SortableAdmin
        tags:
            - {name: sonata.admin, manager_type: orm,group: "tags", show_in_dashboard: true, label: ringSize}

    site_backend.admin.chain.size:
        class: Site\BackendBundle\Admin\ChainSizeAdmin
        arguments:
            - ~
            - Site\BackendBundle\Entity\ChainSize
            - PixSortableBehaviorBundle:SortableAdmin
        tags:
            - {name: sonata.admin, manager_type: orm,group: "tags", show_in_dashboard: true, label: chainSize}

    site_backend.admin.category:
        class: Site\BackendBundle\Admin\CategoryAdmin
        arguments:
            - ~
            - Site\BackendBundle\Entity\Category
            - ~
        tags:
            - {name: sonata.admin, manager_type: orm,group: "category", show_in_dashboard: true, label: category}

    site_backend.admin.sub.category:
        class: Site\BackendBundle\Admin\SubCategoryAdmin
        arguments:
            - ~
            - Site\BackendBundle\Entity\SubCategory
            - ~
        tags:
            - {name: sonata.admin, manager_type: orm,group: "category", show_in_dashboard: true, label: subCategory}

    site_backend.admin.order:
        class: Site\BackendBundle\Admin\OrderAdmin
        arguments:
            - ~
            - Site\BackendBundle\Entity\Order
            - SiteBackendBundle:Order
        tags:
            - {name: sonata.admin, manager_type: orm,group: "order", show_in_dashboard: true, label: order}

    site_backend.admin.xml.log:
        class: Site\BackendBundle\Admin\XmlAdmin
        arguments:
            - ~
            - Site\BackendBundle\Entity\XmlLoadLog
            - ~
        tags:
            - {name: sonata.admin, manager_type: orm, show_in_dashboard: false, label: XmlLog}

    site_backend.admin.load.xml:
        class: Site\BackendBundle\Admin\XmlLoaderAdmin
        arguments:
            - ~
            - Site\BackendBundle\Entity\XmlLoad
            - SiteBackendBundle:XmlLoader
        tags:
            - {name: sonata.admin, manager_type: orm,group: "product", show_in_dashboard: true, label: loadFromFile}

    site_backend.admin.nova_poshta_data:
        class: Site\BackendBundle\Admin\NovaPoshtaAdmin
        arguments:
            - ~
            - Site\BackendBundle\Entity\NovaPoshtaData
            - ~
        tags:
            - {name: sonata.admin, manager_type: orm, show_in_dashboard: false, label: novaPoshta}
########################################################################################################################
    product.flush.listener:
        class: Site\BackendBundle\EventListeners\ProductListener

    set.flush.listener:
        class: Site\BackendBundle\EventListeners\SetListener

    entity.flush.listener:
        class: Site\BackendBundle\EventListeners\FlushListener
        arguments:
            - "@product.flush.listener"
            - "@set.flush.listener"
            - "@newpost.data.update.listener"
        tags:
            - { name: doctrine.event_listener, event: onFlush }
########################################################################################################################
    new.post.service:
        class: Site\BackendBundle\NewPost\NewPostService
        arguments:
            - "@service_container"

    newpost.data.update.listener:
        class: Site\BackendBundle\NewPost\NewPostListener
        arguments:
            - "@new.post.service"

########################################################################################################################
    gedmo.listener.sortable:
        class: Gedmo\Sortable\SortableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

    site_backend.admin.filter_config:
        class: Site\BackendBundle\Admin\FilterConfigAdmin
        arguments: [~, Site\BackendBundle\Entity\FilterConfig, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: FilterConfig }

    site_backend.admin.filter_config_chain_sizes:
        class: Site\BackendBundle\Admin\FilterConfigChainSizesAdmin
        arguments: [~, Site\BackendBundle\Entity\FilterConfigChainSizes, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: FilterConfigChainSizes }

    site_backend.admin.filter_config_insertion_colors:
        class: Site\BackendBundle\Admin\FilterConfigInsertionColorsAdmin
        arguments: [~, Site\BackendBundle\Entity\FilterConfigInsertionColors, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: FilterConfigInsertionColors }

    site_backend.admin.filter_config_insertion_type:
        class: Site\BackendBundle\Admin\FilterConfigInsertionTypeAdmin
        arguments: [~, Site\BackendBundle\Entity\FilterConfigInsertionType, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: FilterConfigInsertionType }

    site_backend.admin.filter_config_product_type:
        class: Site\BackendBundle\Admin\FilterConfigProductTypeAdmin
        arguments: [~, Site\BackendBundle\Entity\FilterConfigProductType, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: FilterConfigProductType }

    site_backend.admin.filter_config_state:
        class: Site\BackendBundle\Admin\FilterConfigStateAdmin
        arguments: [~, Site\BackendBundle\Entity\FilterConfigState, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: FilterConfigState }

    site_backend.admin.filter_config_theme:
        class: Site\BackendBundle\Admin\FilterConfigThemeAdmin
        arguments: [~, Site\BackendBundle\Entity\FilterConfigTheme, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: FilterConfigTheme }

    site_backend.admin.filter_config_theme_value:
        class: Site\BackendBundle\Admin\FilterConfigThemeValueAdmin
        arguments: [~, Site\BackendBundle\Entity\FilterConfigThemeValue, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: FilterConfigThemeValue }
