<?php

namespace Site\BackendBundle\Entity\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCategoriesWithSubCategoriesIndexByTitle(){
        return $this->createQueryBuilder('c','c.title')
            ->leftJoin('c.subCategories','sc')
            ->getQuery()
            ->getResult();
    }
    public function getCategoriesWithSubCategoriesIndexBySlug(){
        return $this->createQueryBuilder('c','c.slug')
            ->leftJoin('c.subCategories','sc')
            ->getQuery()
            ->getResult();
    }
}
