<?php

namespace Site\BackendBundle\Entity\Repository;

/**
 * ChainSizeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChainSizeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getChainSizesIndexByTitle(){
        return $this->createQueryBuilder('chs','chs.title')
            ->getQuery()
            ->getResult();
    }
    public function getAllSortedByTitle(){
        return $this->createQueryBuilder('chs')
            ->orderBy('chs.title', 'ASC')
            ->getQuery();
    }
}
