<?php

namespace Site\BackendBundle\Entity\Repository;

/**
 * FilterConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilterConfigRepository extends \Doctrine\ORM\EntityRepository
{
    public function findFilterConfig()
    {
        return $this->createQueryBuilder('q')
            ->select('q, filterConfigChainSizes, filterConfigInsertionColors,
            filterConfigInsertionType, filterConfigState, filterConfigTheme, filterConfigThemeFilterConfigProductType')
            ->leftJoin('q.filterConfigChainSizes', 'filterConfigChainSizes')
            ->leftJoin('q.filterConfigInsertionColors', 'filterConfigInsertionColors')
            ->leftJoin('q.filterConfigInsertionType', 'filterConfigInsertionType')
            ->leftJoin('q.filterConfigState', 'filterConfigState')
            ->leftJoin('q.filterConfigTheme', 'filterConfigTheme')
            ->leftJoin('filterConfigTheme.filterConfigProductType', 'filterConfigThemeFilterConfigProductType')
            ->getQuery()
            ->getOneOrNullResult();
    }
}
