<?php

namespace Site\BackendBundle\Entity\Repository;

/**
 * InsertionColorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InsertionColorRepository extends \Doctrine\ORM\EntityRepository
{
    public function getInsertionColorsIndexByTitle(){
        return $this->createQueryBuilder('ic','ic.title')
            ->getQuery()
            ->getResult();
    }
    public function getAllSortedByTitle(){
        return $this->createQueryBuilder('ic')
            ->orderBy('ic.title', 'ASC')
            ->getQuery();
    }
}
