<?php

namespace Site\BackendBundle\Entity\Repository;

/**
 * NewsTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsTagRepository extends \Doctrine\ORM\EntityRepository
{
    public function getShareTagsIndexByTitle(){
        return $this->createQueryBuilder('nt','nt.title')
            ->getQuery()
            ->getResult();
    }
    public function getAllSortedByTitle(){
        return $this->createQueryBuilder('nt')
            ->orderBy('nt.title', 'ASC')
            ->getQuery();
    }
}
