<?php

namespace Site\BackendBundle\Entity\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function getProductsIndexByCode(){
        return $this->createQueryBuilder('p','p.cod')
            ->getQuery()
            ->getResult();
    }
    public function getAllSortedByCod(){
        return $this->createQueryBuilder('p')
            ->orderBy('p.cod', 'ASC')
            ->getQuery();
    }
}
