<?php

namespace Site\BackendBundle\Entity\Repository;

/**
 * RingSizeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RingSizeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRingSizesIndexByTitle(){
        return $this->createQueryBuilder('rs','rs.title')
            ->getQuery()
            ->getResult();
    }
    public function getAllSortedByTitle(){
        return $this->createQueryBuilder('rs')
            ->orderBy('rs.title', 'ASC')
            ->getQuery();
    }
}
