<?php

namespace Site\BackendBundle\Entity\Repository;

/**
 * SetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SetRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSetsIndexByCode(){
        return $this->createQueryBuilder('s','s.cod')
            ->getQuery()
            ->getResult();
    }
}
