<?php

namespace Site\BackendBundle\Entity\Repository;

/**
 * ShareTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShareTagRepository extends \Doctrine\ORM\EntityRepository
{
    public function getShareTagsIndexByTitle(){
        return $this->createQueryBuilder('sht','sht.title')
            ->getQuery()
            ->getResult();
    }
    public function getAllSortedByTitle(){
        return $this->createQueryBuilder('sht')
            ->orderBy('sht.title', 'ASC')
            ->getQuery();
    }
}
