<?php

namespace Site\BackendBundle\Entity\Repository;

/**
 * SliderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SliderRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastByNumber($number){
        return $this->createQueryBuilder('s')
            ->setMaxResults($number)
            ->orderBy('s.position','DESC')
            ->getQuery()
            ->getResult()
            ;
    }
}
