<?php

namespace Site\BackendBundle\Entity\Repository;

/**
 * StaticTextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StaticTextRepository extends \Doctrine\ORM\EntityRepository
{
}
